// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ZDGr1alG4QwfMSfMRP0IoFiH8kkzCGg',
    appId: '1:162147926279:web:b5c62e7d89fd65b21a05a2',
    messagingSenderId: '162147926279',
    projectId: 'app-caducidades-51d14',
    authDomain: 'app-caducidades-51d14.firebaseapp.com',
    storageBucket: 'app-caducidades-51d14.firebasestorage.app',
    measurementId: 'G-G5BJHG3CJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMzO2cmMWZpRj8YYYKkbgjl4Yd_-zZQ0',
    appId: '1:162147926279:android:5a8d5ad9da938a4e1a05a2',
    messagingSenderId: '162147926279',
    projectId: 'app-caducidades-51d14',
    storageBucket: 'app-caducidades-51d14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtcGEPECEeU7qAJaqp91-IQ3T3GeKpOk',
    appId: '1:162147926279:ios:f49c88b8acad3a361a05a2',
    messagingSenderId: '162147926279',
    projectId: 'app-caducidades-51d14',
    storageBucket: 'app-caducidades-51d14.firebasestorage.app',
    iosBundleId: 'com.example.caducidadesgourmet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtcGEPECEeU7qAJaqp91-IQ3T3GeKpOk',
    appId: '1:162147926279:ios:f49c88b8acad3a361a05a2',
    messagingSenderId: '162147926279',
    projectId: 'app-caducidades-51d14',
    storageBucket: 'app-caducidades-51d14.firebasestorage.app',
    iosBundleId: 'com.example.caducidadesgourmet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8ZDGr1alG4QwfMSfMRP0IoFiH8kkzCGg',
    appId: '1:162147926279:web:7b397e47fa35832e1a05a2',
    messagingSenderId: '162147926279',
    projectId: 'app-caducidades-51d14',
    authDomain: 'app-caducidades-51d14.firebaseapp.com',
    storageBucket: 'app-caducidades-51d14.firebasestorage.app',
    measurementId: 'G-YS1QHECEWF',
  );
}
